// ------------------------------------------------------------------
// Supabase Generated Types
//
// Purpose:
//   Auto-generated TypeScript types mirroring the database schema.
//   Kept in a separate file because it's overwritten by the
//   `supabase gen types` command.
//
// Responsibility:
//   Provides the Database type used by lib/supabase/server.ts and
//   lib/supabase/client.ts to type SQL queries.
//
// Dependencies:
//   - Generated by: `supabase gen types typescript --local`
//   - Run after every migration change
// -----------------------------------------------------------------/

// When generated, this file exports:
// export type Database = { public: { Tables: { ... } } }

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      analyses: {
        Row: {
          id: string
          url: string
          status: string
          error_message: string | null
          ai_readiness_score: number | null
          seo_score: number | null
          structure_score: number | null
          accessibility_score: number | null
          performance_score: number | null
          discoverability_score: number | null
          overall_score: number | null
          created_at: string
          completed_at: string | null
          raw_response: Json | null
          page_title: string | null
          meta_description: string | null
          h1_count: number | null
          h2_count: number | null
          h3_count: number | null
        }
        Insert: {
          id?: string
          url: string
          status?: string
          error_message?: string | null
        }
        Update: {
          status?: string
          error_message?: string | null
          ai_readiness_score?: number | null
          seo_score?: number | null
          structure_score?: number | null
          accessibility_score?: number | null
          performance_score?: number | null
          discoverability_score?: number | null
          overall_score?: number | null
          completed_at?: string | null
          raw_response?: Json | null
          page_title?: string | null
          meta_description?: string | null
          h1_count?: number | null
          h2_count?: number | null
          h3_count?: number | null
        }
      }
      page_data: {
        Row: {
          id: string
          analysis_id: string
          title: string | null
          meta_description: string | null
          canonical_url: string | null
          robots_directives: string | null
          og_data: Json | null
          twitter_data: Json | null
          structured_data: Json | null
          headings: Json | null
          semantic_elements: Json | null
          accessibility: Json | null
          tech_indicators: Json | null
          html_size_bytes: number | null
          fetched_at: string
        }
        Insert: {
          id?: string
          analysis_id: string
          title?: string | null
          meta_description?: string | null
          canonical_url?: string | null
          robots_directives?: string | null
          og_data?: Json | null
          twitter_data?: Json | null
          structured_data?: Json | null
          headings?: Json | null
          semantic_elements?: Json | null
          accessibility?: Json | null
          tech_indicators?: Json | null
          html_size_bytes?: number | null
        }
      }
      core_web_vitals: {
        Row: {
          id: string
          analysis_id: string
          lcp: number | null
          fid: number | null
          inp: number | null
          cls: number | null
          performance_score: number | null
          raw_response: Json | null
        }
        Insert: {
          id?: string
          analysis_id: string
          lcp?: number | null
          fid?: number | null
          inp?: number | null
          cls?: number | null
          performance_score?: number | null
          raw_response?: Json | null
        }
      }
      ai_analysis: {
        Row: {
          id: string
          analysis_id: string
          gemini_model: string
          prompt_tokens: number | null
          summary: string | null
          recommendations: Json | null
          strengths: Json | null
          weaknesses: Json | null
          raw_response: Json | null
        }
        Insert: {
          id?: string
          analysis_id: string
          gemini_model: string
          prompt_tokens?: number | null
          summary?: string | null
          recommendations?: Json | null
          strengths?: Json | null
          weaknesses?: Json | null
          raw_response?: Json | null
        }
      }
    }
  }
}
