ALTER TABLE public.analyses
  ADD COLUMN IF NOT EXISTS raw_response JSONB;

ALTER TABLE public.analyses
  ADD COLUMN IF NOT EXISTS page_title TEXT,
  ADD COLUMN IF NOT EXISTS meta_description TEXT,
  ADD COLUMN IF NOT EXISTS h1_count INTEGER,
  ADD COLUMN IF NOT EXISTS h2_count INTEGER,
  ADD COLUMN IF NOT EXISTS h3_count INTEGER;
